// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmpjxmjhhxrsncyzqmwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcGp4bWpoaHhyc25jeXpxbXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTEzODEsImV4cCI6MjA2NTYyNzM4MX0.rUiznqBSZfdiEfiEvIaIErBsC_VsYuLxFw3Yh7IYJb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);